spring:
  datasource:
    url: jdbc:mysql://<HOST>:<PORT>/<DBNAME>?useSSL=true&requireSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: <USERNAME>
    password: <PASSWORD>
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true